---
- hosts: all
  sudo: true
  roles:
  - base

# Run this without sudo
- hosts: dotfiles
  roles:
  - dotfiles

- hosts: desktop
  sudo: true
  roles:
  - dropbox
  - chrome
  - skype
  - tools
  - virtualization
  - i3wm
