---
- name: Install Homeshick
  git: repo=git://github.com/andsens/homeshick.git
       dest=/home/{{ ansible_user_id }}/.homesick/repos/homeshick
       update=yes
       accept_hostkey=yes
- name: Check for dotfiles
  stat: path=/home/{{ ansible_user_id }}/.homesick/repos/dotfiles
  register: dotfiles
- name: Clone dotfiles
  shell: /home/{{ ansible_user_id }}/.homesick/repos/homeshick/bin/homeshick clone --batch {{ dotfiles_repo }}
  when: dotfiles.stat.exists == false
- name: Pull dotfiles
  shell: /home/{{ ansible_user_id }}/.homesick/repos/homeshick/bin/homeshick pull --batch dotfiles
  when: dotfiles.stat.exists == true
- name: Symlink dotfiles
  shell: /home/{{ ansible_user_id }}/.homesick/repos/homeshick/bin/homeshick symlink --batch dotfiles
- name: Change shell to zsh
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh
  sudo: yes
