---
- name: Install the KeePass Plugin PPA
  apt_repository: repo='ppa:dlech/keepass2-plugins'
- name: Install Tools
  apt: pkg={{ item }} state=latest
  with_items:
  - mono-complete
  - keepass2
  - keepass2-plugin-keeagent
  - keepass2-plugin-keepasshttp
  - keepass2-plugin-application-indicator
