---
- name: Install the KeePass Plugin PPA
  command: add-apt-repository -y ppa:dlech/keepass2-plugins
- name: Update Aptitude
  apt: update_cache=yes
- name: Install Tools
  apt: pkg={{ item }} state=latest
  with_items:
  - mono-complete
  - keepass2
  - keepass2-plugin-keeagent
  - keepass2-plugin-keepasshttp
  - keepass2-plugin-application-indicator
