---
- name: Install i3
  apt: pkg={{ item }} state=present
  with_items:
  - i3
  - i3-wm
  - i3status
  - i3lock

- name: Install py3status dependencies
  apt: pkg={{ item }} state=present
  with_items:
  - python-stdeb
  - python-all
- name: Install py3status
  command: pypi-install py3status
