---
- name: Install an updated PPA
  command: add-apt-repository -y ppa:pi-rho/dev
- name: Install the Git Maintainers PPA
  command: add-apt-repository -y ppa:git-core/ppa

- name: Update Apt
  apt: update_cache=yes

- name: Install useful applications
  apt: pkg={{ item }} state=latest
  with_items:
  - git
  - man
  - tmux
  - vim
  - zsh
